options:
  merge-default-rules: true
  formatter: checkstyle
  output-file: 'reports/sass-lint.checkstyle.xml'

files:
  include: '$MODULE_PATH/**/*.sass'
  ignore: '**/_shame.sass'

rules:
  mixins-before-declarations: 0
  no-css-comments: 0
  no-duplicate-properties:
    - 1
    - exclude:
      - display
      - padding
      - padding-top
      - padding-right
      - padding-bottom
      - padding-left
      - margin
      - margin-top
      - margin-right
      - margin-bottom
      - margin-left
      - border
      - border-top
      - border-right
      - border-bottom
      - border-left
      - border-radius
      - width
      - height
      - max-width
      - max-height
      - font-size
      - line-height
      - left
      - right
      - top
      - bottom
  class-name-format:
    - 1
    -
      convention: 'strictbem'
  indentation:
    - 2
    - size: 'tab'
  leading-zero:
    - 1
    - include: true
  property-sort-order:
    - 1
    - order: 'smacss'
